apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: my-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /usr/local/bin/ksops
files:
  - secrets.encrypted.yaml
