apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: ddns-server
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: ddns-database
  template:
    metadata:
      labels:
        app: ddns-database
    spec:
      containers:
        - name: database
          image: nelsontlima/ddns-db:test
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: ddns-server-config
            - secretRef:
                name: ddns-server-secrets
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
