apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddnsserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NelsonTLima/platform-infra.git
    targetRevision: HEAD
    path: k8s/apps/ddns-server
  destination:
    server: https://kubernetes.default.svc
    namespace: ddns-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
